### ISSUE TITLE
Issue with two PWM boards operation (RIGHT and LEFT slot on the same arduino)

### ISSUE THREAD

**Issue by santkumar** [FYNCH-BIO/evolver-arduino#15]
When initializing both the right and left slot PWM using "Tlc.init(RIGHT_PWM | LEFT_PWM, 4095)", the LEFT PWM works properly but the RIGHT PWM is unable to reach absolute zero. 

If only the RIGHT PWM is initialized using "Tlc.init(RIGHT_PWM, 4095)", then it works properly (can reach absolute zero) but obviously we don't get LEFT slot PWM working in this case. 

Need some fix in the Tlc5940_SAMD library.

**Comment by zheins** [comment]
Fixed by #17
