### ISSUE TITLE
Bad failure mode for chemostat with flow rate = 0

### ISSUE THREAD

**Issue by cpmancuso** [FYNCH-BIO/evolver-arduino#4]
If a fluidic command is sent with timeToPump=0 and pumpInterval=0 and numberTimesToPump=-1, then pumps turn on and run continuously. This is an intuitive command to send if turning off a single pump in chemostat mode. Seems to work if timeToPump is 0 and pump interval is non zero, or if numberTimesToPump is 0 (i.e. single pump event). 

Can be fixed in dpu code as a special exception (i.e. in updateChemo(), if pumpInterval=0, then change numberTimesToPump to 0), but might be good to prevent future errors.

**Comment by zheins** [comment]
I think this was fixed. Closing unless it comes up again.
